import { h } from 'vue'
import type { IconSet, IconProps } from 'vuetify'
import { mdi as mdiSvg } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccessPoint,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiArrowUp,
  mdiBell,
  mdiBroom,
  mdiChartBar,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiCircleDouble,
  mdiClockAlertOutline,
  mdiClose,
  mdiCog,
  mdiContentSave,
  mdiCrosshairsGps,
  mdiDelete,
  mdiEye,
  mdiEyeOff,
  mdiFire,
  mdiFormatListBulleted,
  mdiGrid,
  mdiHelp,
  mdiHome,
  mdiInformationOutline,
  mdiKeyOutline,
  mdiKeyboardOutline,
  mdiLayers,
  mdiMagnify,
  mdiMap,
  mdiMapMarkerPath,
  mdiMapMarkerQuestion,
  mdiMapMarkerRadius,
  mdiMessageText,
  mdiMessageTextOutline,
  mdiNotificationClearAll,
  mdiOpenInNew,
  mdiPause,
  mdiPencil,
  mdiPlay,
  mdiPlus,
  mdiRadar,
  mdiRadioTower,
  mdiRadiusOutline,
  mdiRefresh,
  mdiReply,
  mdiSignal,
  mdiSineWave,
  mdiSkipNext,
  mdiSkipPrevious,
  mdiStar,
  mdiStarOutline,
  mdiTextBoxOutline,
  mdiTuneVariant,
  mdiWeatherLightning,
  mdiWeatherNight,
  mdiWeatherPartlyCloudy,
  mdiWeatherRainy,
  mdiWeatherSunny,
  mdiWeatherWindy,
  mdiWifiOff,
} from '@mdi/js'

// Maps the app's existing `mdi-*` icon strings to tree-shaken SVG paths so
// the 400 kB icon font (and its CSS) stays out of the bundle. Add an entry
// here when using a new icon; unmapped names render nothing and warn.
const paths: Record<string, string> = {
  'mdi-access-point': mdiAccessPoint,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-bell': mdiBell,
  'mdi-broom': mdiBroom,
  'mdi-chart-bar': mdiChartBar,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-circle-double': mdiCircleDouble,
  'mdi-clock-alert-outline': mdiClockAlertOutline,
  'mdi-close': mdiClose,
  'mdi-cog': mdiCog,
  'mdi-content-save': mdiContentSave,
  'mdi-crosshairs-gps': mdiCrosshairsGps,
  'mdi-delete': mdiDelete,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-fire': mdiFire,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-grid': mdiGrid,
  'mdi-help': mdiHelp,
  'mdi-home': mdiHome,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-key-outline': mdiKeyOutline,
  'mdi-keyboard-outline': mdiKeyboardOutline,
  'mdi-layers': mdiLayers,
  'mdi-magnify': mdiMagnify,
  'mdi-map': mdiMap,
  'mdi-map-marker-path': mdiMapMarkerPath,
  'mdi-map-marker-question': mdiMapMarkerQuestion,
  'mdi-map-marker-radius': mdiMapMarkerRadius,
  'mdi-message-text': mdiMessageText,
  'mdi-message-text-outline': mdiMessageTextOutline,
  'mdi-notification-clear-all': mdiNotificationClearAll,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-pause': mdiPause,
  'mdi-pencil': mdiPencil,
  'mdi-play': mdiPlay,
  'mdi-plus': mdiPlus,
  'mdi-radar': mdiRadar,
  'mdi-radio-tower': mdiRadioTower,
  'mdi-radius-outline': mdiRadiusOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-reply': mdiReply,
  'mdi-signal': mdiSignal,
  'mdi-sine-wave': mdiSineWave,
  'mdi-skip-next': mdiSkipNext,
  'mdi-skip-previous': mdiSkipPrevious,
  'mdi-star': mdiStar,
  'mdi-star-outline': mdiStarOutline,
  'mdi-text-box-outline': mdiTextBoxOutline,
  'mdi-tune-variant': mdiTuneVariant,
  'mdi-weather-lightning': mdiWeatherLightning,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-partly-cloudy': mdiWeatherPartlyCloudy,
  'mdi-weather-rainy': mdiWeatherRainy,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-weather-windy': mdiWeatherWindy,
  'mdi-wifi-off': mdiWifiOff,
}

export const mdiKebab: IconSet = {
  component: (props: IconProps) => {
    const name = props.icon
    let icon = name
    if (typeof name === 'string' && name.startsWith('mdi-')) {
      const path = paths[name]
      if (path) {
        icon = path
      } else {
        console.warn(`Unmapped MDI icon: ${name} — add it to src/plugins/mdiIcons.ts`)
        icon = ''
      }
    }
    return h(mdiSvg.component, { ...props, icon })
  },
}
