// <auto-generated />
using System;
using DireControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DireControl.Migrations
{
    [DbContext(typeof(DireControlContext))]
    [Migration("20260321204055_AddAggregatedStatisticsTables")]
    partial class AddAggregatedStatisticsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DireControl.Data.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("DireControl.Data.Models.CoverageGridStatistic", b =>
                {
                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgLat")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgLon")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacketCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("GridSquare");

                    b.ToTable("CoverageGridStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.DigiConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasUsed")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigipeaterCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DigipeaterLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("DigipeaterLon")
                        .HasColumnType("REAL");

                    b.Property<int>("OwnBeaconId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondsAfterBeacon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnBeaconId");

                    b.ToTable("DigiConfirmations");
                });

            modelBuilder.Entity("DireControl.Data.Models.DigipeaterStatistic", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<int>("HopPositionCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HopPositionSum")
                        .HasColumnType("REAL");

                    b.Property<int>("Last24hPackets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPacketsForwarded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Callsign");

                    b.ToTable("DigipeaterStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnEnter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnExit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Geofences");
                });

            modelBuilder.Entity("DireControl.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AckSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathUsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReplySent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("RetryState", "NextRetryAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeaconedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Heading")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HopCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PathUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("RadioId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RadioId", "BeaconedAt");

                    b.ToTable("OwnBeacons");
                });

            modelBuilder.Entity("DireControl.Data.Models.Packet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int>("HopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KissChannel")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MessageData")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParsedType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPacket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryData")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnknownHopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeatherData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("StationCallsign");

                    b.HasIndex("StationCallsign", "ReceivedAt");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("DireControl.Data.Models.ProximityRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMetres")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetCallsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProximityRules");
                });

            modelBuilder.Entity("DireControl.Data.Models.Radio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconComment")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconPath")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconSymbol")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullCallsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ssid")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullCallsign");

                    b.HasIndex("IsActive");

                    b.ToTable("Radios");
                });

            modelBuilder.Entity("DireControl.Data.Models.Station", b =>
                {
                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeardVia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnWatchList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeatherStation")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastAltitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("LastHeading")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeardAprsIs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeardRf")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastLon")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("QrzLookupData")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Callsign");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DireControl.Data.Models.StationStatistic", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<double>("AveragePacketsPerHour")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestGapMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Callsign");

                    b.ToTable("StationStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AprsIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AprsIsFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AprsIsHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AprsIsPasscode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AprsIsPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeduplicationWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenWeatherMapApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadarProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RainViewerProApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TomorrowIoApiKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AprsIsEnabled = false,
                            AprsIsFilter = "r/39.0/-98.0/500 t/m",
                            AprsIsHost = "rotate.aprs2.net",
                            AprsIsPort = 14580,
                            DeduplicationWindowSeconds = 60,
                            OutboundPath = "WIDE1-1,WIDE2-1",
                            RadarProvider = 0
                        });
                });

            modelBuilder.Entity("DireControl.Data.Models.DigiConfirmation", b =>
                {
                    b.HasOne("DireControl.Data.Models.OwnBeacon", "OwnBeacon")
                        .WithMany("Confirmations")
                        .HasForeignKey("OwnBeaconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnBeacon");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.HasOne("DireControl.Data.Models.Radio", "Radio")
                        .WithMany("Beacons")
                        .HasForeignKey("RadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("DireControl.Data.Models.Packet", b =>
                {
                    b.HasOne("DireControl.Data.Models.Station", "Station")
                        .WithMany("Packets")
                        .HasForeignKey("StationCallsign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DireControl.Data.Models.StationStatistic", b =>
                {
                    b.HasOne("DireControl.Data.Models.Station", "Station")
                        .WithOne("Statistics")
                        .HasForeignKey("DireControl.Data.Models.StationStatistic", "Callsign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("DireControl.Data.Models.Radio", b =>
                {
                    b.Navigation("Beacons");
                });

            modelBuilder.Entity("DireControl.Data.Models.Station", b =>
                {
                    b.Navigation("Packets");

                    b.Navigation("Statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
