// <auto-generated />
using System;
using DireControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DireControl.Migrations
{
    [DbContext(typeof(DireControlContext))]
    partial class DireControlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("DireControl.Data.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAcknowledged");

                    b.HasIndex("TriggeredAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("DireControl.Data.Models.CoverageGridStatistic", b =>
                {
                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgLat")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgLon")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PacketCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("GridSquare");

                    b.ToTable("CoverageGridStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.DigiConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasUsed")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigipeaterCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DigipeaterLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("DigipeaterLon")
                        .HasColumnType("REAL");

                    b.Property<int>("OwnBeaconId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondsAfterBeacon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnBeaconId");

                    b.ToTable("DigiConfirmations");
                });

            modelBuilder.Entity("DireControl.Data.Models.DigipeaterStatistic", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<int>("HopPositionCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HopPositionSum")
                        .HasColumnType("REAL");

                    b.Property<int>("Last24hPackets")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPacketsForwarded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Callsign");

                    b.ToTable("DigipeaterStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnEnter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlertOnExit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Geofences");
                });

            modelBuilder.Entity("DireControl.Data.Models.LogLevelOverride", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Category");

                    b.ToTable("LogLevelOverrides");
                });

            modelBuilder.Entity("DireControl.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AckSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathUsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReplySent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("RetryState", "NextRetryAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeaconedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Heading")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Heard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("HopCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PathUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("RadioId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RadioId", "BeaconedAt");

                    b.ToTable("OwnBeacons");
                });

            modelBuilder.Entity("DireControl.Data.Models.Packet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int>("HopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KissChannel")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MessageData")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParsedType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParserVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPacket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalData")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationCallsign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryData")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnknownHopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeatherData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParserVersion");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("StationCallsign");

                    b.HasIndex("StationCallsign", "ReceivedAt");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("DireControl.Data.Models.PmsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKilled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KilledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsKilled");

                    b.HasIndex("ToCallsign");

                    b.ToTable("PmsMessages");
                });

            modelBuilder.Entity("DireControl.Data.Models.ProximityRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMetres")
                        .HasColumnType("REAL");

                    b.Property<string>("TargetCallsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProximityRules");
                });

            modelBuilder.Entity("DireControl.Data.Models.Radio", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoBeaconEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoBeaconIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeaconComment")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconPath")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BeaconSymbol")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FrequencyMhz")
                        .HasColumnType("REAL");

                    b.Property<string>("FullCallsign")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModemCaptureDevice")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModemEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModemPlaybackDevice")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PttGpioActiveLow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PttGpioChip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PttGpioLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PttHidDevice")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PttHidPin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PttMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PttRigctldHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("PttRigctldPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PttSerialPort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PttSerialUseDtr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PttSerialUseRts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ssid")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("TxAudioLevelPct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TxDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TxEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TxPersistence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TxSlotTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TxTailMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FullCallsign");

                    b.HasIndex("IsActive");

                    b.ToTable("Radios");
                });

            modelBuilder.Entity("DireControl.Data.Models.Station", b =>
                {
                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("GridSquare")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeardVia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnWatchList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeatherStation")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LastAltitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LastFrequencyMhz")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastHeading")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHeardAprsIs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeardRf")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("LastLon")
                        .HasColumnType("REAL");

                    b.Property<string>("LastMode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LastSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("QrzLookupData")
                        .HasColumnType("TEXT");

                    b.Property<int>("StationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Callsign");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("DireControl.Data.Models.StationStatistic", b =>
                {
                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<double>("AveragePacketsPerHour")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongestGapMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Callsign");

                    b.ToTable("StationStatistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalMacro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppendCr")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("TerminalMacros");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigiPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalCallsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Params")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RemoteCallsign", "Channel", "DigiPath")
                        .IsUnique();

                    b.ToTable("TerminalPresets");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalSessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesIn")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DigiPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteCallsign")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StartedAt");

                    b.ToTable("TerminalSessionRecords");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalTranscriptChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalSessionRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerminalSessionRecordId", "Id");

                    b.ToTable("TerminalTranscriptChunks");
                });

            modelBuilder.Entity("DireControl.Data.Models.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgwpeServerBindAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AgwpeServerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgwpeServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AprsIsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AprsIsFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AprsIsHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AprsIsPasscode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AprsIsPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedModeDefaultPaclen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConnectedModeInboundEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedModeMaxSessions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConnectedModePreferMod128")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedModeRetries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedModeT1Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedModeWindowSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeduplicationWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DigipeaterEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DigipeaterFillInOnly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DigipeaterMaxWideN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DirewolfEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirewolfHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DirewolfPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DirewolfReconnectDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HomeLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("HomeLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsToRfGatingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsToRfPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsToRfRecentHeardMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KissServerEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KissServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenWeatherMapApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OurCallsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacketRetentionAprsIsDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketRetentionOwnDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketRetentionRfDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PmsBannerText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PmsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PmsRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PmsSsid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RadarProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RainViewerProApiKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RfToIsGatingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalTranscriptRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TomorrowIoApiKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgwpeServerBindAddress = "127.0.0.1",
                            AgwpeServerEnabled = false,
                            AgwpeServerPort = 8000,
                            AprsIsEnabled = false,
                            AprsIsFilter = "r/39.0/-98.0/500",
                            AprsIsHost = "rotate.aprs2.net",
                            AprsIsPort = 14580,
                            ConnectedModeDefaultPaclen = 128,
                            ConnectedModeInboundEnabled = false,
                            ConnectedModeMaxSessions = 10,
                            ConnectedModePreferMod128 = false,
                            ConnectedModeRetries = 10,
                            ConnectedModeT1Seconds = 3,
                            ConnectedModeWindowSize = 4,
                            DeduplicationWindowSeconds = 60,
                            DigipeaterEnabled = false,
                            DigipeaterFillInOnly = false,
                            DigipeaterMaxWideN = 2,
                            DirewolfEnabled = false,
                            DirewolfHost = "localhost",
                            DirewolfPort = 8001,
                            DirewolfReconnectDelaySeconds = 5,
                            IsToRfGatingEnabled = false,
                            IsToRfPath = "",
                            IsToRfRecentHeardMinutes = 30,
                            KissServerEnabled = false,
                            KissServerPort = 8010,
                            OutboundPath = "WIDE1-1,WIDE2-1",
                            PacketRetentionAprsIsDays = 14,
                            PacketRetentionOwnDays = 0,
                            PacketRetentionRfDays = 0,
                            PmsBannerText = "Welcome to the DireControl mailbox. H for help.",
                            PmsEnabled = false,
                            PmsRetentionDays = 0,
                            PmsSsid = 1,
                            RadarProvider = 0,
                            RfToIsGatingEnabled = false,
                            TerminalTranscriptRetentionDays = 90
                        });
                });

            modelBuilder.Entity("DireControl.Data.Models.DigiConfirmation", b =>
                {
                    b.HasOne("DireControl.Data.Models.OwnBeacon", "OwnBeacon")
                        .WithMany("Confirmations")
                        .HasForeignKey("OwnBeaconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnBeacon");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.HasOne("DireControl.Data.Models.Radio", "Radio")
                        .WithMany("Beacons")
                        .HasForeignKey("RadioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radio");
                });

            modelBuilder.Entity("DireControl.Data.Models.Packet", b =>
                {
                    b.HasOne("DireControl.Data.Models.Station", "Station")
                        .WithMany("Packets")
                        .HasForeignKey("StationCallsign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DireControl.Data.Models.StationStatistic", b =>
                {
                    b.HasOne("DireControl.Data.Models.Station", "Station")
                        .WithOne("Statistics")
                        .HasForeignKey("DireControl.Data.Models.StationStatistic", "Callsign")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalTranscriptChunk", b =>
                {
                    b.HasOne("DireControl.Data.Models.TerminalSessionRecord", "TerminalSessionRecord")
                        .WithMany("Chunks")
                        .HasForeignKey("TerminalSessionRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerminalSessionRecord");
                });

            modelBuilder.Entity("DireControl.Data.Models.OwnBeacon", b =>
                {
                    b.Navigation("Confirmations");
                });

            modelBuilder.Entity("DireControl.Data.Models.Radio", b =>
                {
                    b.Navigation("Beacons");
                });

            modelBuilder.Entity("DireControl.Data.Models.Station", b =>
                {
                    b.Navigation("Packets");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("DireControl.Data.Models.TerminalSessionRecord", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
